### ISSUE TITLE
Check compliance with xdist

### ISSUE THREAD

**Issue by smarie** [smarie/python-pytest-harvest#1]

**Comment by humbienri** [comment]
Hello,

Any traction on this? I am contemplating using this pytest "plugin" but wonder if it'll be something that will eventually trip us up when we choose to parallelize our tests in the future.

Thank you :)

**Comment by smarie** [comment]
Thanks for the feedback ! Well the best idea would be to test :) I actually do not master xdist at all, that's why I left that aside until someone with at least some experience of it would get me started.

So if you are able to provide a minimal reproducible example, do not hesitate to post it here ;) ; if that leads to a bug, I'll try to fix it. If not, we'll close this ticket.

**Comment by humbienri** [comment]
Good to know, thank you.

**Comment by smarie** [comment]
See #32 that has more details - we can close this one now
