### ISSUE TITLE
Unable to use module_results_dct as described

### ISSUE THREAD

**Issue by AndrewFalanga** [smarie/python-pytest-harvest#37]
Hello,

Starting an issue as you'd mentioned in StackOverflow.  In attempting to use these instructions, https://smarie.github.io/python-pytest-harvest/, I am not able to access the components of the pytest-harvest module as described.

As an example, the below results only in module_results_dct as being undefined.

    import numpy as np
    def test_abs():
        assert np.abs(-3) == 3
        print("module_results_dct keys")
        for k in module_results_dct:
            print("   - " + k)

I did `pip3 install pytest-harvest` to install the modules.  I am sure that I'm doing something incorrectly.  This morning, while perusing the git-hub sources (something I didn't do yesterday) I did find some things about installing, via pip, what's in the `ci_tools` subdirectory.  This I have not done because I did not clone the repo.

**Comment by smarie** [comment]
I think you just forgot to require the fixture :)

```python
import numpy as np

def test_abs(module_results_dct):
    assert np.abs(-3) == 3
    print("module_results_dct keys")
    for k in module_results_dct:
        print("   - " + k)
```

See pytest documentation to better understand what are fixtures and how they should be used. pytest-harvest "just" provides new ones, but does not provide any additional/fancy mechanism, it is really plain pytest here.

**Comment by AndrewFalanga** [comment]
Ah, I see.  Thank you for the pointer.  In fact, I'm quite new to pytest.
It's a research project for work.

Thank you again.

Andy

**Comment by smarie** [comment]
You're welcome. Closing the ticket now, feel free to open another one if you encounter a specific issue.
