### ISSUE TITLE
[Improvement Request] Only import pandas if needed

### ISSUE THREAD

**Issue by jmrgibson** [smarie/python-pytest-harvest#49]
Firstly, thanks for the great plugin, especially the documentation!

I'm trying to speed up the init time of our pytest suite (ie, speed up the time before we actually start running tests), because our users often iterate on one test at a time, which typically take 1-3 seconds to run. Importing pandas is currently ~0.5sec of our boot up time, coming from pytest-harvest. A small fraction of our tests use pandas, and where we use it, we've been careful to delay the import until the functions that use it, so that we don't pay this penalty across all tests. 

From a cursory glance, [this line](https://github.com/smarie/python-pytest-harvest/blob/86a259bcb7ac09a643d42a447d7c2e791e403159/pytest_harvest/plugin.py#L223) and [this line](https://github.com/smarie/python-pytest-harvest/blob/86a259bcb7ac09a643d42a447d7c2e791e403159/pytest_harvest/plugin.py#L296)  could be moved inside the `get_session_results_df()` function definition, and the error message re-worked, so that you only pay the import cost if you use the function, rather than every time you load the plugin. 

If this sounds OK, I can put up a PR changing this.

**Comment by smarie** [comment]
This seems reasonable @jmrgibson  thanks ! I'll check for your PR

**Comment by smarie** [comment]
Fixed by fe5860a 
Will be available in 1.10.3 in a few minutes. Thanks again @jmrgibson  !
