### ISSUE TITLE
contribute pytest-harvest to conda-forge

### ISSUE THREAD

**Issue by harelwa** [smarie/python-pytest-harvest#57]
Hi,

I've created this PR in `conda-forge` so `pytest-harvest` can be installed as a conda package as well.

https://github.com/conda-forge/staged-recipes/pull/18647

Thanks,

Harel

**Comment by harelwa** [comment]
It's done - https://anaconda.org/conda-forge/pytest-harvest

**Comment by smarie** [comment]
So nice, thanks a lot @harelwa !
